// Code generated by graphql-codegen. DO NOT EDIT.
// Source: internal/graphql/schema.graphql
// Regenerate: cd gui && npm run codegen

export type Maybe<T> = T | null;
export type InputMaybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export interface Scalars {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  JSON: { input: Record<string, unknown>; output: Record<string, unknown>; }
}

export interface ApiCalls {
  failed: Scalars['Int']['output'];
  success: Scalars['Int']['output'];
  total: Scalars['Int']['output'];
}

export interface AgentTask {
  completedAt?: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['String']['output'];
  error?: Maybe<Scalars['String']['output']>;
  metadata?: Maybe<Scalars['JSON']['output']>;
  projectRoot?: Maybe<Scalars['String']['output']>;
  result?: Maybe<Scalars['String']['output']>;
  role: Scalars['String']['output'];
  status: Scalars['String']['output'];
  task: Scalars['String']['output'];
  taskID: Scalars['String']['output'];
  updatedAt: Scalars['String']['output'];
}

export interface BeadsTask {
  dependencies?: Maybe<Array<Scalars['String']['output']>>;
  description: Scalars['String']['output'];
  id: Scalars['String']['output'];
  metadata?: Maybe<Scalars['JSON']['output']>;
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
}

export interface CloseResult {
  message?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
  taskID: Scalars['String']['output'];
}

export interface CostSavings {
  actualCost: Scalars['Float']['output'];
  avgCostPerTask: Scalars['Float']['output'];
  baselineCost: Scalars['Float']['output'];
  savings: Scalars['Float']['output'];
  savingsPercent: Scalars['Float']['output'];
  totalTasks: Scalars['Int']['output'];
}

export interface DeleteResult {
  message?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
  taskID: Scalars['String']['output'];
}

export interface ExecutionEvent {
  durationMs?: Maybe<Scalars['Int']['output']>;
  error?: Maybe<Scalars['String']['output']>;
  eventType: Scalars['String']['output'];
  metadata?: Maybe<Scalars['JSON']['output']>;
  result?: Maybe<Scalars['String']['output']>;
  role: Scalars['String']['output'];
  status?: Maybe<Scalars['String']['output']>;
  task: Scalars['String']['output'];
  taskID: Scalars['String']['output'];
  timestamp: Scalars['String']['output'];
}

export interface GradeSummary {
  byModel: Scalars['JSON']['output'];
  byRole: Scalars['JSON']['output'];
  costSavings: CostSavings;
  gradeDistribution: Scalars['JSON']['output'];
  modelTiers: Scalars['JSON']['output'];
  totalGrades: Scalars['Int']['output'];
}

export interface HttpMetrics {
  errors: Scalars['Int']['output'];
  totalRequests: Scalars['Int']['output'];
}

export interface HealthStatus {
  features: Scalars['JSON']['output'];
  server: Scalars['String']['output'];
  status: Scalars['String']['output'];
  version: Scalars['String']['output'];
}

export interface LogEntry {
  attributes?: Maybe<Scalars['JSON']['output']>;
  level: Scalars['String']['output'];
  message: Scalars['String']['output'];
  timestamp: Scalars['String']['output'];
}

export interface Metrics {
  apiCalls: ApiCalls;
  averageDurationMs: Scalars['Float']['output'];
  averageTokensPerTask: Scalars['Int']['output'];
  http: HttpMetrics;
  performance: Performance;
  providerBreakdown: Array<ProviderUsage>;
  rateLimiting: RateLimiting;
  sessionMetrics: SessionMetrics;
  streaming: StreamingMetrics;
  tasksActive: Scalars['Int']['output'];
  tasksCompleted: Scalars['Int']['output'];
  tasksFailed: Scalars['Int']['output'];
  tasksSpawned: Scalars['Int']['output'];
  tokenUsage: TokenUsage;
  turnMetrics: TurnMetrics;
}

export interface Mutation {
  cancelAgent: Scalars['Boolean']['output'];
  closeTask: CloseResult;
  deleteTask: DeleteResult;
  retryTask: RetryResult;
  spawnAgent: AgentTask;
  updateTaskStatus: AgentTask;
}


export interface MutationCancelAgentArgs {
  taskID: Scalars['String']['input'];
}


export interface MutationCloseTaskArgs {
  taskID: Scalars['String']['input'];
}


export interface MutationDeleteTaskArgs {
  taskID: Scalars['String']['input'];
}


export interface MutationRetryTaskArgs {
  taskID: Scalars['String']['input'];
}


export interface MutationSpawnAgentArgs {
  projectRoot?: InputMaybe<Scalars['String']['input']>;
  role: Scalars['String']['input'];
  task: Scalars['String']['input'];
}


export interface MutationUpdateTaskStatusArgs {
  status: Scalars['String']['input'];
  taskID: Scalars['String']['input'];
}

export interface Performance {
  uptime: Scalars['String']['output'];
}

export interface PerformanceGrade {
  averageExecutionTime: Scalars['Float']['output'];
  averageTokens: Scalars['Int']['output'];
  confidenceScore: Scalars['Float']['output'];
  downgradeCount: Scalars['Int']['output'];
  escalationCount: Scalars['Int']['output'];
  failures: Scalars['Int']['output'];
  firstUsed: Scalars['String']['output'];
  grade: Scalars['String']['output'];
  lastUsed: Scalars['String']['output'];
  modelID: Scalars['String']['output'];
  projectID: Scalars['String']['output'];
  retries: Scalars['Int']['output'];
  retryRate: Scalars['Float']['output'];
  roleID: Scalars['String']['output'];
  source: Scalars['String']['output'];
  successRate: Scalars['Float']['output'];
  successes: Scalars['Int']['output'];
  totalAttempts: Scalars['Int']['output'];
}

export interface ProjectCost {
  projectName: Scalars['String']['output'];
  projectRoot: Scalars['String']['output'];
  providerBreakdown: Array<ProviderCost>;
  totalCost: Scalars['Float']['output'];
  totalInputTokens: Scalars['Int']['output'];
  totalOutputTokens: Scalars['Int']['output'];
}

export interface ProviderCost {
  calls: Scalars['Int']['output'];
  cost: Scalars['Float']['output'];
  inputTokens: Scalars['Int']['output'];
  model: Scalars['String']['output'];
  outputTokens: Scalars['Int']['output'];
  provider: Scalars['String']['output'];
}

export interface ProviderUsage {
  calls: Scalars['Int']['output'];
  inputTokens: Scalars['Int']['output'];
  model: Scalars['String']['output'];
  outputTokens: Scalars['Int']['output'];
  provider: Scalars['String']['output'];
}

export interface Query {
  beadsTask?: Maybe<BeadsTask>;
  beadsTasks: Array<BeadsTask>;
  executionEventsByTask: Array<ExecutionEvent>;
  executionLog: Array<ExecutionEvent>;
  health: HealthStatus;
  logs: Array<LogEntry>;
  metrics: Metrics;
  performance: Performance;
  performanceByProject: Array<PerformanceGrade>;
  performanceByRole: Array<PerformanceGrade>;
  performanceGrades: Array<PerformanceGrade>;
  performanceSummary: GradeSummary;
  projectCosts: Array<ProjectCost>;
  task?: Maybe<AgentTask>;
  taskHistory: Array<TaskSummary>;
  tasks: Array<AgentTask>;
}


export interface QueryBeadsTaskArgs {
  id: Scalars['String']['input'];
}


export interface QueryBeadsTasksArgs {
  status?: InputMaybe<Scalars['String']['input']>;
}


export interface QueryExecutionEventsByTaskArgs {
  taskID: Scalars['String']['input'];
}


export interface QueryExecutionLogArgs {
  limit?: InputMaybe<Scalars['Int']['input']>;
}


export interface QueryLogsArgs {
  level?: InputMaybe<Scalars['String']['input']>;
  limit?: InputMaybe<Scalars['Int']['input']>;
}


export interface QueryPerformanceByProjectArgs {
  project: Scalars['String']['input'];
}


export interface QueryPerformanceByRoleArgs {
  role: Scalars['String']['input'];
}


export interface QueryTaskArgs {
  taskID: Scalars['String']['input'];
}


export interface QueryTaskHistoryArgs {
  limit?: InputMaybe<Scalars['Int']['input']>;
}

export interface RateLimiting {
  violations: Scalars['Int']['output'];
}

export interface RetryResult {
  message?: Maybe<Scalars['String']['output']>;
  success: Scalars['Boolean']['output'];
  taskID: Scalars['String']['output'];
}

export interface SessionData {
  inputTokens: Scalars['Int']['output'];
  outputTokens: Scalars['Int']['output'];
  taskID: Scalars['String']['output'];
  turnCount: Scalars['Int']['output'];
}

export interface SessionMetrics {
  recentSessions: Array<SessionData>;
}

export interface StreamingMetrics {
  active: Scalars['Int']['output'];
  closed: Scalars['Int']['output'];
  opened: Scalars['Int']['output'];
}

export interface Subscription {
  logStream: LogEntry;
  metricsUpdated: Metrics;
  taskUpdated: AgentTask;
}


export interface SubscriptionLogStreamArgs {
  level?: InputMaybe<Scalars['String']['input']>;
}


export interface SubscriptionTaskUpdatedArgs {
  taskID?: InputMaybe<Scalars['String']['input']>;
}

export interface TaskSummary {
  created: Scalars['String']['output'];
  durationMs: Scalars['Int']['output'];
  error?: Maybe<Scalars['String']['output']>;
  events: Array<Scalars['String']['output']>;
  result?: Maybe<Scalars['String']['output']>;
  role: Scalars['String']['output'];
  status: Scalars['String']['output'];
  task: Scalars['String']['output'];
  taskID: Scalars['String']['output'];
  updated: Scalars['String']['output'];
}

export interface TokenUsage {
  inputTokens: Scalars['Int']['output'];
  outputTokens: Scalars['Int']['output'];
  totalTokens: Scalars['Int']['output'];
}

export interface TurnData {
  durationMs: Scalars['Int']['output'];
  inputTokens: Scalars['Int']['output'];
  outputTokens: Scalars['Int']['output'];
  taskID: Scalars['String']['output'];
  turn: Scalars['Int']['output'];
}

export interface TurnMetrics {
  avgInputPerTurn: Scalars['Int']['output'];
  avgOutputPerTurn: Scalars['Int']['output'];
  recentTurns: Array<TurnData>;
  totalTurns: Scalars['Int']['output'];
}
