import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: '../internal/graphql/schema.graphql',
  generates: {
    'src/types/graphql-types.ts': {
      plugins: [
        {
          add: {
            content: [
              '// Code generated by graphql-codegen. DO NOT EDIT.',
              '// Source: internal/graphql/schema.graphql',
              '// Regenerate: cd gui && npm run codegen',
              '',
            ].join('\n'),
          },
        },
        'typescript',
      ],
      config: {
        // Map the GraphQL JSON scalar to TypeScript's Record<string, unknown>
        scalars: {
          JSON: 'Record<string, unknown>',
        },
        // Emit interfaces for consistency with rest of codebase
        declarationKind: 'interface',
        // Skip __typename field (not used in REST-like queries)
        skipTypename: true,
        // Optional fields use T | null
        maybeValue: 'T | null',
      },
    },
  },
}

export default config
