import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AI-Pack Documentation Sidebar
 *
 * This sidebar structure mirrors the AI-Pack framework organization.
 * Additional sections will be enabled as content is migrated.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'claude-code-configuration',
    {
      type: 'category',
      label: 'Framework',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'framework',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quality Gates',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'gates',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quality Standards',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quality',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integration',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration',
        },
      ],
    },
  ],
};

export default sidebars;
