import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AI-Pack Documentation Sidebar
 *
 * Plugin-first structure: what ai-pack ships (agents, skills, kg),
 * then generic engineering guidance (workflows, quality standards).
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'agents',
    'skills',
    'knowledge-graph',
    'task-packets',
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quality Standards',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quality',
        },
      ],
    },
  ],
};

export default sidebars;
