// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AgentTask struct {
	TaskID      string         `json:"taskID"`
	Role        string         `json:"role"`
	Task        string         `json:"task"`
	Status      string         `json:"status"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	CompletedAt *string        `json:"completedAt,omitempty"`
	Result      *string        `json:"result,omitempty"`
	Error       *string        `json:"error,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	BeadsTaskID *string        `json:"beadsTaskID,omitempty"`
	ProjectRoot *string        `json:"projectRoot,omitempty"`
}

type BeadsTask struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Dependencies []string       `json:"dependencies,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
}

type HealthStatus struct {
	Status   string         `json:"status"`
	Version  string         `json:"version"`
	Server   string         `json:"server"`
	Features map[string]any `json:"features"`
}

type LogEntry struct {
	Timestamp  string         `json:"timestamp"`
	Level      string         `json:"level"`
	Message    string         `json:"message"`
	Attributes map[string]any `json:"attributes,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RetryResult struct {
	Success bool    `json:"success"`
	TaskID  string  `json:"taskID"`
	Message *string `json:"message,omitempty"`
}

type Subscription struct {
}
