// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AgentTask struct {
	TaskID      string         `json:"taskID"`
	Role        string         `json:"role"`
	Task        string         `json:"task"`
	Status      string         `json:"status"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
	CompletedAt *string        `json:"completedAt,omitempty"`
	Result      *string        `json:"result,omitempty"`
	Error       *string        `json:"error,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	ProjectRoot *string        `json:"projectRoot,omitempty"`
}

type BeadsTask struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Dependencies []string       `json:"dependencies,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
}

type CloseResult struct {
	Success bool    `json:"success"`
	TaskID  string  `json:"taskID"`
	Message *string `json:"message,omitempty"`
}

type CostSavings struct {
	BaselineCost   float64 `json:"baselineCost"`
	ActualCost     float64 `json:"actualCost"`
	Savings        float64 `json:"savings"`
	SavingsPercent float64 `json:"savingsPercent"`
	TotalTasks     int     `json:"totalTasks"`
	AvgCostPerTask float64 `json:"avgCostPerTask"`
}

type ExecutionEvent struct {
	EventType  string         `json:"eventType"`
	TaskID     string         `json:"taskID"`
	Role       string         `json:"role"`
	Task       string         `json:"task"`
	Timestamp  string         `json:"timestamp"`
	Status     *string        `json:"status,omitempty"`
	Error      *string        `json:"error,omitempty"`
	DurationMs *int           `json:"durationMs,omitempty"`
	Result     *string        `json:"result,omitempty"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

type GradeSummary struct {
	TotalGrades       int            `json:"totalGrades"`
	GradeDistribution map[string]any `json:"gradeDistribution"`
	ByRole            map[string]any `json:"byRole"`
	ByModel           map[string]any `json:"byModel"`
	ModelTiers        map[string]any `json:"modelTiers"`
	CostSavings       *CostSavings   `json:"costSavings"`
}

type HealthStatus struct {
	Status   string         `json:"status"`
	Version  string         `json:"version"`
	Server   string         `json:"server"`
	Features map[string]any `json:"features"`
}

type LogEntry struct {
	Timestamp  string         `json:"timestamp"`
	Level      string         `json:"level"`
	Message    string         `json:"message"`
	Attributes map[string]any `json:"attributes,omitempty"`
}

type Mutation struct {
}

type PerformanceGrade struct {
	ModelID              string  `json:"modelID"`
	RoleID               string  `json:"roleID"`
	ProjectID            string  `json:"projectID"`
	TotalAttempts        int     `json:"totalAttempts"`
	Successes            int     `json:"successes"`
	Failures             int     `json:"failures"`
	Retries              int     `json:"retries"`
	SuccessRate          float64 `json:"successRate"`
	RetryRate            float64 `json:"retryRate"`
	Grade                string  `json:"grade"`
	ConfidenceScore      float64 `json:"confidenceScore"`
	AverageTokens        int     `json:"averageTokens"`
	AverageExecutionTime float64 `json:"averageExecutionTime"`
	EscalationCount      int     `json:"escalationCount"`
	DowngradeCount       int     `json:"downgradeCount"`
	LastUsed             string  `json:"lastUsed"`
	FirstUsed            string  `json:"firstUsed"`
}

type Query struct {
}

type RetryResult struct {
	Success bool    `json:"success"`
	TaskID  string  `json:"taskID"`
	Message *string `json:"message,omitempty"`
}

type Subscription struct {
}

type TaskSummary struct {
	TaskID     string   `json:"taskID"`
	Role       string   `json:"role"`
	Task       string   `json:"task"`
	Status     string   `json:"status"`
	Created    string   `json:"created"`
	Updated    string   `json:"updated"`
	DurationMs int      `json:"durationMs"`
	Error      *string  `json:"error,omitempty"`
	Result     *string  `json:"result,omitempty"`
	Events     []string `json:"events"`
}
