package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
)

// SpawnAgent is the resolver for the spawnAgent field.
func (r *mutationResolver) SpawnAgent(ctx context.Context, role string, taskID string) (*SpawnResult, error) {
	root := ""
	if projectRoot != nil {
		root = *projectRoot
	}

	taskInfo, err := r.server.SpawnAgent(role, task, root)
	if err != nil {
		return nil, err
	}

	return convertTaskInfoToGraphQL(taskInfo), nil
}

// CancelAgent is the resolver for the cancelAgent field.
func (r *mutationResolver) CancelAgent(ctx context.Context, taskID string) (bool, error) {
	// Task cancellation not yet implemented in server
	// Would require adding cancellation support to AgentServer
	return false, nil
}

// UpdateTaskStatus is the resolver for the updateTaskStatus field.
func (r *mutationResolver) UpdateTaskStatus(ctx context.Context, id string, status BeadsTaskStatus) (*BeadsTask, error) {
	// Task status updates not yet implemented in server
	// Would require adding status update support to AgentServer
	taskInfo, err := r.server.GetTaskStatus(taskID)
	if err != nil {
		return nil, err
	}
	return convertTaskInfoToGraphQL(taskInfo), nil
}

// StartTask is the resolver for the startTask field.
func (r *mutationResolver) StartTask(ctx context.Context, id string) (*BeadsTask, error) {
	panic(fmt.Errorf("not implemented: StartTask - startTask"))
}

// CloseTask is the resolver for the closeTask field.
func (r *mutationResolver) CloseTask(ctx context.Context, id string) (*BeadsTask, error) {
	panic(fmt.Errorf("not implemented: CloseTask - closeTask"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*ServerHealth, error) {
	features := map[string]interface{}{
		"graphql":       true,
		"rest":          true,
		"a2a_protocol":  true,
		"sse_streaming": true,
	}

	return &HealthStatus{
		Status:   "healthy",
		Version:  "1.0.0",
		Server:   "a2a-agent",
		Features: features,
	}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, status *TaskStatus) ([]*AgentTask, error) {
	tasksMap := r.server.GetActiveTasks()
	result := make([]*AgentTask, 0, len(tasksMap))

	for _, taskInfo := range tasksMap {
		gqlTask := convertTaskInfoToGraphQL(taskInfo)
		result = append(result, gqlTask)
	}

	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*AgentTask, error) {
	taskInfo, err := r.server.GetTaskStatus(taskID)
	if err != nil {
		return nil, err
	}

	return convertTaskInfoToGraphQL(taskInfo), nil
}

// BeadsTask is the resolver for the beadsTask field.
func (r *queryResolver) BeadsTask(ctx context.Context, id string) (*BeadsTask, error) {
	// Beads integration not yet implemented
	// Would require adding Beads client to resolver
	return nil, nil
}

// BeadsTasks is the resolver for the beadsTasks field.
func (r *queryResolver) BeadsTasks(ctx context.Context, status *BeadsTaskStatus) ([]*BeadsTask, error) {
	// Beads integration not yet implemented
	// Would require adding Beads client to resolver
	return []*BeadsTask{}, nil
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context) (*Metrics, error) {
	metricsInfo := r.server.GetMetrics()

	return &Metrics{
		TasksSpawned:      metricsInfo.TasksSpawned,
		TasksCompleted:    metricsInfo.TasksCompleted,
		TasksFailed:       metricsInfo.TasksFailed,
		TasksActive:       metricsInfo.TasksActive,
		AverageDurationMs: metricsInfo.AverageDurationMs,
		TokenUsage: &TokenUsage{
			TotalTokens:  int(metricsInfo.TotalTokens),
			InputTokens:  int(metricsInfo.InputTokens),
			OutputTokens: int(metricsInfo.OutputTokens),
		},
		APICalls: &APICalls{
			Total:   int(metricsInfo.APICalls),
			Success: int(metricsInfo.APISuccess),
			Failed:  int(metricsInfo.APIFailed),
		},
		Performance: &Performance{
			CPUUsage:      metricsInfo.CPUUsage,
			MemoryUsageMb: metricsInfo.MemoryUsageMB,
			Goroutines:    metricsInfo.Goroutines,
			Uptime:        metricsInfo.Uptime,
		},
	}, nil
}

// Performance is the resolver for the performance field.
func (r *queryResolver) Performance(ctx context.Context) (*Performance, error) {
	metricsInfo := r.server.GetMetrics()

	return &Performance{
		CPUUsage:      metricsInfo.CPUUsage,
		MemoryUsageMb: metricsInfo.MemoryUsageMB,
		Goroutines:    metricsInfo.Goroutines,
		Uptime:        metricsInfo.Uptime,
	}, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, taskID string, limit *int) ([]*LogEntry, error) {
	// Log querying not yet implemented
	// Would require adding log management to server
	return []*LogEntry{}, nil
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, taskID *string) (<-chan *AgentTask, error) {
	ch := make(chan *AgentTask, 100)

	// Task subscriptions not yet implemented
	// Would require adding task subscription support
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// LogStream is the resolver for the logStream field.
func (r *subscriptionResolver) LogStream(ctx context.Context, taskID string) (<-chan *LogEntry, error) {
	ch := make(chan *LogEntry, 100)

	// Log streaming not yet implemented
	// Would require adding log subscription support
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// MetricsUpdated is the resolver for the metricsUpdated field.
func (r *subscriptionResolver) MetricsUpdated(ctx context.Context) (<-chan *Metrics, error) {
	ch := make(chan *Metrics, 10)

	// Metrics subscriptions not yet implemented
	// Would require adding metrics subscription support
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func convertTaskInfoToGraphQL(info *TaskInfo) *AgentTask {
	task := &AgentTask{
		TaskID:    info.TaskID,
		Role:      info.Role,
		Task:      info.Task,
		Status:    info.Status,
		Progress:  info.Progress,
		CreatedAt: info.CreatedAt,
		UpdatedAt: info.UpdatedAt,
	}

	if info.CompletedAt != nil {
		task.CompletedAt = info.CompletedAt
	}
	if info.Result != nil {
		task.Result = info.Result
	}
	if info.Error != nil {
		task.Error = info.Error
	}
	if info.BeadsTaskID != nil {
		task.BeadsTaskID = info.BeadsTaskID
	}
	if info.Metadata != nil {
		// Convert map[string]string to map[string]any
		metadata := make(map[string]any)
		for k, v := range info.Metadata {
			metadata[k] = v
		}
		task.Metadata = metadata
	}

	return task
}
*/
