package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
)

// Helper function to create string pointer
func stringPtr(s string) *string {
	return &s
}

// SpawnAgent is the resolver for the spawnAgent field.
func (r *mutationResolver) SpawnAgent(ctx context.Context, role string, task string, projectRoot *string) (*AgentTask, error) {
	panic(fmt.Errorf("not implemented: SpawnAgent - spawnAgent"))
}

// CancelAgent is the resolver for the cancelAgent field.
func (r *mutationResolver) CancelAgent(ctx context.Context, taskID string) (bool, error) {
	panic(fmt.Errorf("not implemented: CancelAgent - cancelAgent"))
}

// UpdateTaskStatus is the resolver for the updateTaskStatus field.
func (r *mutationResolver) UpdateTaskStatus(ctx context.Context, taskID string, status string) (*AgentTask, error) {
	panic(fmt.Errorf("not implemented: UpdateTaskStatus - updateTaskStatus"))
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationResolver) RetryTask(ctx context.Context, taskID string) (*RetryResult, error) {
	// Get the failed task info
	taskInfo, err := r.server.GetTaskStatus(taskID)
	if err != nil {
		return &RetryResult{
			Success: false,
			TaskID:  taskID,
			Message: stringPtr("Task not found: " + err.Error()),
		}, nil
	}

	// Spawn a new agent task with the same parameters
	newTask, err := r.server.SpawnAgent(taskInfo.Role, taskInfo.Task, "")
	if err != nil {
		return &RetryResult{
			Success: false,
			TaskID:  taskID,
			Message: stringPtr("Failed to retry task: " + err.Error()),
		}, nil
	}

	return &RetryResult{
		Success: true,
		TaskID:  newTask.TaskID,
		Message: stringPtr("Task retried successfully. New task ID: " + newTask.TaskID),
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthStatus, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*AgentTask, error) {
	activeTasks := r.server.GetActiveTasks()

	tasks := make([]*AgentTask, 0, len(activeTasks))
	for _, taskInfo := range activeTasks {
		// Convert metadata from map[string]string to map[string]any
		metadata := make(map[string]any)
		for k, v := range taskInfo.Metadata {
			metadata[k] = v
		}

		tasks = append(tasks, &AgentTask{
			TaskID:      taskInfo.TaskID,
			Role:        taskInfo.Role,
			Task:        taskInfo.Task,
			Status:      taskInfo.Status,
			Progress:    taskInfo.Progress,
			CreatedAt:   taskInfo.CreatedAt,
			UpdatedAt:   taskInfo.UpdatedAt,
			CompletedAt: taskInfo.CompletedAt,
			Result:      taskInfo.Result,
			Error:       taskInfo.Error,
			Metadata:    metadata,
			BeadsTaskID: taskInfo.BeadsTaskID,
		})
	}

	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, taskID string) (*AgentTask, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// BeadsTasks is the resolver for the beadsTasks field.
func (r *queryResolver) BeadsTasks(ctx context.Context, status *string) ([]*BeadsTask, error) {
	panic(fmt.Errorf("not implemented: BeadsTasks - beadsTasks"))
}

// BeadsTask is the resolver for the beadsTask field.
func (r *queryResolver) BeadsTask(ctx context.Context, id string) (*BeadsTask, error) {
	panic(fmt.Errorf("not implemented: BeadsTask - beadsTask"))
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context) (*Metrics, error) {
	metricsInfo := r.server.GetMetrics()

	// Convert recent turns
	recentTurns := make([]TurnData, len(metricsInfo.RecentTurns))
	for i, turn := range metricsInfo.RecentTurns {
		recentTurns[i] = TurnData{
			TaskID:       turn.TaskID,
			Turn:         int(turn.Turn),
			InputTokens:  int(turn.InputTokens),
			OutputTokens: int(turn.OutputTokens),
			DurationMs:   int(turn.DurationMs),
		}
	}

	// Convert recent sessions
	recentSessions := make([]SessionData, len(metricsInfo.RecentSessions))
	for i, session := range metricsInfo.RecentSessions {
		recentSessions[i] = SessionData{
			TaskID:       session.TaskID,
			InputTokens:  int(session.InputTokens),
			OutputTokens: int(session.OutputTokens),
			TurnCount:    int(session.TurnCount),
		}
	}

	return &Metrics{
		TasksSpawned:         metricsInfo.TasksSpawned,
		TasksCompleted:       metricsInfo.TasksCompleted,
		TasksFailed:          metricsInfo.TasksFailed,
		TasksActive:          metricsInfo.TasksActive,
		AverageDurationMs:    metricsInfo.AverageDurationMs,
		AverageTokensPerTask: int(metricsInfo.AverageTokensPerTask),
		TokenUsage: &TokenUsage{
			TotalTokens:  int(metricsInfo.TotalTokens),
			InputTokens:  int(metricsInfo.InputTokens),
			OutputTokens: int(metricsInfo.OutputTokens),
		},
		APICalls: &APICalls{
			Total:   int(metricsInfo.APICalls),
			Success: int(metricsInfo.APISuccess),
			Failed:  int(metricsInfo.APIFailed),
		},
		Performance: &Performance{
			CPUUsage: metricsInfo.CPUUsage,
			Uptime:   metricsInfo.Uptime,
		},
		TurnMetrics: &TurnMetrics{
			TotalTurns:       int(metricsInfo.TotalTurns),
			AvgInputPerTurn:  int(metricsInfo.AvgInputPerTurn),
			AvgOutputPerTurn: int(metricsInfo.AvgOutputPerTurn),
			RecentTurns:      recentTurns,
		},
		SessionMetrics: &SessionMetrics{
			RecentSessions: recentSessions,
		},
		Streaming: &StreamingMetrics{
			Opened: int(metricsInfo.StreamsOpened),
			Closed: int(metricsInfo.StreamsClosed),
			Active: int(metricsInfo.StreamsActive),
		},
		HTTP: &HTTPMetrics{
			TotalRequests: int(metricsInfo.HTTPRequestsTotal),
			Errors:        int(metricsInfo.HTTPErrors),
		},
		RateLimiting: &RateLimiting{
			Violations: int(metricsInfo.RateLimitViolations),
		},
	}, nil
}

// Performance is the resolver for the performance field.
func (r *queryResolver) Performance(ctx context.Context) (*Performance, error) {
	panic(fmt.Errorf("not implemented: Performance - performance"))
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, limit *int, level *string) ([]*LogEntry, error) {
	panic(fmt.Errorf("not implemented: Logs - logs"))
}

// LogStream is the resolver for the logStream field.
func (r *subscriptionResolver) LogStream(ctx context.Context, level *string) (<-chan *LogEntry, error) {
	panic(fmt.Errorf("not implemented: LogStream - logStream"))
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, taskID *string) (<-chan *AgentTask, error) {
	panic(fmt.Errorf("not implemented: TaskUpdated - taskUpdated"))
}

// MetricsUpdated is the resolver for the metricsUpdated field.
func (r *subscriptionResolver) MetricsUpdated(ctx context.Context) (<-chan *Metrics, error) {
	panic(fmt.Errorf("not implemented: MetricsUpdated - metricsUpdated"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func stringPtr(s string) *string {
	return &s
}
*/
