package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/cortexa-llc/ai-pack/internal/monitoring"
)

// SpawnAgent is the resolver for the spawnAgent field.
func (r *mutationResolver) SpawnAgent(ctx context.Context, role string, task string, projectRoot *string) (*AgentTask, error) {
	root := ""
	if projectRoot != nil {
		root = *projectRoot
	}
	taskInfo, err := r.server.SpawnAgent(role, task, root)
	if err != nil {
		msg := err.Error()
		return &AgentTask{
			Role:      role,
			Task:      task,
			Status:    TaskStatusFailed,
			UpdatedAt: time.Now().Format(time.RFC3339),
			Success:   false,
			Message:   &msg,
		}, nil
	}
	result := convertTaskInfoToGraphQL(taskInfo)
	msg := fmt.Sprintf("Agent %s started (task %s)", role, result.TaskID)
	result.Success = true
	result.Message = &msg
	return result, nil
}

// CancelAgent is the resolver for the cancelAgent field.
func (r *mutationResolver) CancelAgent(ctx context.Context, taskID string) (bool, error) {
	if err := r.server.CancelTask(taskID); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateTaskStatus is the resolver for the updateTaskStatus field.
func (r *mutationResolver) UpdateTaskStatus(ctx context.Context, taskID string, status string) (*AgentTask, error) {
	// TODO: Implement task status update logic
	return &AgentTask{
		TaskID:    taskID,
		Status:    status,
		UpdatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

// RetryTask is the resolver for the retryTask field.
func (r *mutationResolver) RetryTask(ctx context.Context, taskID string) (*RetryResult, error) {
	// TODO: Implement retry task logic
	return &RetryResult{
		Success: true,
		TaskID:  taskID,
		Message: nil,
	}, nil
}

// CloseTask is the resolver for the closeTask field.
func (r *mutationResolver) CloseTask(ctx context.Context, taskID string) (*CloseResult, error) {
	if err := r.server.CloseTask(taskID); err != nil {
		msg := err.Error()
		return &CloseResult{Success: false, TaskID: taskID, Message: &msg}, nil
	}
	return &CloseResult{Success: true, TaskID: taskID, Message: nil}, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, taskID string) (*DeleteResult, error) {
	if err := r.server.DeleteTask(taskID); err != nil {
		msg := err.Error()
		return &DeleteResult{Success: false, TaskID: taskID, Message: &msg}, nil
	}
	return &DeleteResult{Success: true, TaskID: taskID, Message: nil}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthStatus, error) {
	return &HealthStatus{
		Status:  "healthy",
		Version: "2.1.0",
		Server:  "a2a-agent",
		Features: &HealthFeatures{
			GraphQL:           true,
			Rest:              true,
			A2aProtocol:       true,
			SseStreaming:      true,
			Monitoring:        true,
			ParallelExecution: true,
		},
	}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, status *string) ([]*AgentTask, error) {
	if r.server == nil {
		return []*AgentTask{}, nil
	}

	tasksMap := r.server.GetAllTasks()
	tasks := make([]*AgentTask, 0, len(tasksMap))

	for _, taskInfo := range tasksMap {
		task := convertTaskInfoToGraphQL(taskInfo)
		if status != nil && task.Status != *status {
			continue
		}
		tasks = append(tasks, task)
	}

	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, taskID string) (*AgentTask, error) {
	if r.server == nil {
		return nil, fmt.Errorf("server not available")
	}

	taskInfo, err := r.server.GetTaskStatus(taskID)
	if err != nil {
		return nil, err
	}

	return convertTaskInfoToAgentTask(taskInfo), nil
}

// BeadsTasks is the resolver for the beadsTasks field.
func (r *queryResolver) BeadsTasks(ctx context.Context, status *string) ([]*BeadsTask, error) {
	// TODO: Implement Beads tasks query
	return []*BeadsTask{}, nil
}

// BeadsTask is the resolver for the beadsTask field.
func (r *queryResolver) BeadsTask(ctx context.Context, id string) (*BeadsTask, error) {
	// Beads integration not yet implemented
	// Would require adding Beads client to resolver
	return nil, nil
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context) (*Metrics, error) {
	metricsInfo := r.server.GetMetrics()

	inputTokens := int(metricsInfo.InputTokens)
	outputTokens := int(metricsInfo.OutputTokens)
	apiTotal := int(metricsInfo.APICalls)
	apiSuccess := int(metricsInfo.APISuccess)
	apiFailed := int(metricsInfo.APIFailed)

	return &Metrics{
		TasksSpawned:      metricsInfo.TasksSpawned,
		TasksCompleted:    metricsInfo.TasksCompleted,
		TasksFailed:       metricsInfo.TasksFailed,
		TasksActive:       metricsInfo.TasksActive,
		TasksInProgress:   metricsInfo.TasksActive,
		AverageDurationMs: metricsInfo.AverageDurationMs,
		AvgDurationMs:     metricsInfo.AverageDurationMs,
		TotalInputTokens:  inputTokens,
		TotalOutputTokens: outputTokens,
		APICallsTotal:     apiTotal,
		APICallsSuccess:   apiSuccess,
		APICallsFailed:    apiFailed,
		TokenUsage: &TokenUsage{
			TotalTokens:  int(metricsInfo.TotalTokens),
			InputTokens:  inputTokens,
			OutputTokens: outputTokens,
		},
		APICalls: &APICalls{
			Total:   apiTotal,
			Success: apiSuccess,
			Failed:  apiFailed,
		},
		Performance: &Performance{
			Uptime: metricsInfo.Uptime,
		},
	}, nil
}

// Performance is the resolver for the performance field.
func (r *queryResolver) Performance(ctx context.Context) (*Performance, error) {
	metricsInfo := r.server.GetMetrics()
	perf := &Performance{
		Uptime: metricsInfo.Uptime,
	}
	if r.monitor != nil {
		snap := r.monitor.GetSnapshot()
		perf.TaskTokenUsage = snap.TaskTokenUsage
		perf.RecentTurns = snap.TurnTokenData
	}
	return perf, nil
}

// Logs is the resolver for the logs field.
func (r *queryResolver) Logs(ctx context.Context, limit *int, level *string) ([]*LogEntry, error) {
	// TODO: Implement logs query
	return []*LogEntry{}, nil
}

// ExecutionLog is the resolver for the executionLog field.
func (r *queryResolver) ExecutionLog(ctx context.Context, limit *int) ([]*ExecutionEvent, error) {
	// TODO: Implement execution log query
	return []*ExecutionEvent{}, nil
}

// TaskHistory is the resolver for the taskHistory field.
func (r *queryResolver) TaskHistory(ctx context.Context, limit *int) ([]*TaskSummary, error) {
	// TODO: Implement task history query
	return []*TaskSummary{}, nil
}

// ExecutionEventsByTask is the resolver for the executionEventsByTask field.
func (r *queryResolver) ExecutionEventsByTask(ctx context.Context, taskID string) ([]*ExecutionEvent, error) {
	// TODO: Implement execution events by task query
	return []*ExecutionEvent{}, nil
}

// PerformanceGrades is the resolver for the performanceGrades field.
func (r *queryResolver) PerformanceGrades(ctx context.Context) ([]*PerformanceGrade, error) {
	if monitoring.GlobalGradeManager == nil {
		return []*PerformanceGrade{}, nil
	}

	monitoringGrades := monitoring.GlobalGradeManager.GetAllGrades()
	grades := make([]*PerformanceGrade, 0, len(monitoringGrades))

	for _, mg := range monitoringGrades {
		grades = append(grades, convertMonitoringGrade(mg))
	}

	return grades, nil
}

// PerformanceSummary is the resolver for the performanceSummary field.
func (r *queryResolver) PerformanceSummary(ctx context.Context) (*GradeSummary, error) {
	if monitoring.GlobalGradeManager == nil {
		return &GradeSummary{
			TotalGrades:       0,
			GradeDistribution: make(map[string]interface{}),
			ByRole:            make(map[string]interface{}),
			ByModel:           make(map[string]interface{}),
			CostSavings: &CostSavings{
				BaselineCost:   0,
				ActualCost:     0,
				Savings:        0,
				SavingsPercent: 0,
				TotalTasks:     0,
				AvgCostPerTask: 0,
			},
		}, nil
	}

	monitoringSummary := monitoring.GlobalGradeManager.GetSummary()

	// Convert grade distribution
	gradeDistribution := make(map[string]interface{})
	for grade, count := range monitoringSummary.GradeDistribution {
		gradeDistribution[grade] = count
	}

	// Convert by role
	byRole := make(map[string]interface{})
	for role, summary := range monitoringSummary.ByRole {
		byRole[role] = map[string]interface{}{
			"totalAttempts": summary.TotalAttempts,
			"successes":     summary.Successes,
			"failures":      summary.Failures,
			"successRate":   summary.SuccessRate,
			"models":        summary.Models,
		}
	}

	// Convert by model
	byModel := make(map[string]interface{})
	for model, summary := range monitoringSummary.ByModel {
		byModel[model] = map[string]interface{}{
			"totalAttempts": summary.TotalAttempts,
			"successes":     summary.Successes,
			"failures":      summary.Failures,
			"successRate":   summary.SuccessRate,
			"averageGrade":  summary.AverageGrade,
		}
	}

	// Calculate cost savings from metrics
	costSavings := calculateCostSavings()

	// Build model tiers info from the canonical ModelsByTier registry
	tierOrder := []monitoring.ModelTier{
		monitoring.TierMinimal,
		monitoring.TierLow,
		monitoring.TierMedium,
		monitoring.TierHigh,
	}
	tierNames := map[monitoring.ModelTier]string{
		monitoring.TierMinimal: "Minimal",
		monitoring.TierLow:     "Low",
		monitoring.TierMedium:  "Medium",
		monitoring.TierHigh:    "High",
	}
	tiers := make([]map[string]interface{}, 0, len(tierOrder))
	for _, tier := range tierOrder {
		models := monitoring.ModelsByTier[tier]
		modelIDs := make([]string, 0, len(models))
		for _, m := range models {
			modelIDs = append(modelIDs, m.ID)
		}
		tiers = append(tiers, map[string]interface{}{
			"tier":   int(tier),
			"name":   tierNames[tier],
			"models": modelIDs,
		})
	}
	modelTiersInfo := map[string]any{"tiers": tiers}

	return &GradeSummary{
		TotalGrades:       monitoringSummary.TotalGrades,
		GradeDistribution: gradeDistribution,
		ByRole:            byRole,
		ByModel:           byModel,
		ModelTiers:        modelTiersInfo,
		CostSavings:       costSavings,
	}, nil
}

// PerformanceByRole is the resolver for the performanceByRole field.
func (r *queryResolver) PerformanceByRole(ctx context.Context, role string) ([]*PerformanceGrade, error) {
	if monitoring.GlobalGradeManager == nil {
		return []*PerformanceGrade{}, nil
	}

	monitoringGrades := monitoring.GlobalGradeManager.GetGradesByRole(role)
	grades := make([]*PerformanceGrade, 0, len(monitoringGrades))

	for _, mg := range monitoringGrades {
		grades = append(grades, convertMonitoringGrade(mg))
	}

	return grades, nil
}

// PerformanceByProject is the resolver for the performanceByProject field.
func (r *queryResolver) PerformanceByProject(ctx context.Context, project string) ([]*PerformanceGrade, error) {
	if monitoring.GlobalGradeManager == nil {
		return []*PerformanceGrade{}, nil
	}

	monitoringGrades := monitoring.GlobalGradeManager.GetGradesByProject(monitoring.ProjectIDFromPath(project))
	grades := make([]*PerformanceGrade, 0, len(monitoringGrades))

	for _, mg := range monitoringGrades {
		grades = append(grades, convertMonitoringGrade(mg))
	}

	return grades, nil
}

// ProjectCosts is the resolver for the projectCosts field.
func (r *queryResolver) ProjectCosts(ctx context.Context) ([]*ProjectCost, error) {
	if r.server == nil {
		return []*ProjectCost{}, nil
	}

	// Get project costs data from server
	projectsData, err := r.server.GetProjectCostsData()
	if err != nil {
		return []*ProjectCost{}, nil
	}

	result := make([]*ProjectCost, 0, len(projectsData))
	for _, data := range projectsData {
		// Convert provider breakdown
		providersData := data["providerBreakdown"].([]map[string]interface{})
		providerCosts := make([]*ProviderCost, 0, len(providersData))

		for _, p := range providersData {
			providerCosts = append(providerCosts, &ProviderCost{
				Provider:     p["provider"].(string),
				Model:        p["model"].(string),
				Calls:        int(p["calls"].(int64)),
				InputTokens:  int(p["inputTokens"].(int64)),
				OutputTokens: int(p["outputTokens"].(int64)),
				Cost:         p["cost"].(float64),
			})
		}

		result = append(result, &ProjectCost{
			ProjectRoot:       data["projectRoot"].(string),
			ProjectName:       data["projectName"].(string),
			TotalCost:         data["totalCost"].(float64),
			TotalInputTokens:  int(data["totalInputTokens"].(int64)),
			TotalOutputTokens: int(data["totalOutputTokens"].(int64)),
			ProviderBreakdown: providerCosts,
		})
	}

	return result, nil
}

// LogStream is the resolver for the logStream field.
func (r *subscriptionResolver) LogStream(ctx context.Context, level *string) (<-chan *LogEntry, error) {
	ch := make(chan *LogEntry, 100)

	// TODO: Implement log streaming
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// TaskUpdated is the resolver for the taskUpdated field.
func (r *subscriptionResolver) TaskUpdated(ctx context.Context, taskID *string) (<-chan *AgentTask, error) {
	ch := make(chan *AgentTask, 100)

	// Task subscriptions not yet implemented
	// Would require adding task subscription support
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// MetricsUpdated is the resolver for the metricsUpdated field.
func (r *subscriptionResolver) MetricsUpdated(ctx context.Context) (<-chan *Metrics, error) {
	ch := make(chan *Metrics, 10)

	// Metrics subscriptions not yet implemented
	// Would require adding metrics subscription support
	go func() {
		defer close(ch)
		<-ctx.Done()
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
