#!/bin/bash
# GitHub MCP Integration Script for AI-Pack
# Version: 1.0.0
# Date: 2026-01-18
#
# This script provides GitHub MCP integration capabilities:
# - CI/CD workflow monitoring and failure handling
# - Issue/Epic/Story creation from Beads tasks
# - PR management and quality gate checks
# - Beads ↔ GitHub synchronization
#
# Prerequisites:
# - GitHub MCP server running (docker or native)
# - GITHUB_TOKEN environment variable set
# - jq installed for JSON parsing
# - Beads (bd) installed

set -e

# Configuration
GITHUB_MCP_URL="${GITHUB_MCP_URL:-http://localhost:3000}"
GITHUB_REPO="${GITHUB_REPO:-$(git config --get remote.origin.url | sed 's/.*github.com[:/]\(.*\)\.git/\1/')}"
GITHUB_TOKEN="${GITHUB_TOKEN}"

if [ -z "$GITHUB_TOKEN" ]; then
  echo "❌ Error: GITHUB_TOKEN not set"
  exit 1
fi

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper: Call GitHub MCP API
github_mcp_call() {
  local endpoint="$1"
  local method="${2:-GET}"
  local data="${3:-}"

  local curl_cmd="curl -s -X ${method} \
    -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
    -H 'Content-Type: application/json' \
    ${GITHUB_MCP_URL}${endpoint}"

  if [ -n "$data" ]; then
    curl_cmd="${curl_cmd} -d '${data}'"
  fi

  eval $curl_cmd
}

# Helper: Call GitHub API directly (for features not in MCP yet)
github_api_call() {
  local endpoint="$1"
  local method="${2:-GET}"
  local data="${3:-}"

  local curl_cmd="curl -s -X ${method} \
    -H 'Authorization: token ${GITHUB_TOKEN}' \
    -H 'Accept: application/vnd.github.v3+json' \
    https://api.github.com${endpoint}"

  if [ -n "$data" ]; then
    curl_cmd="${curl_cmd} -d '${data}'"
  fi

  eval $curl_cmd
}

#==============================================================================
# FEATURE 1: CI/CD Workflow Monitoring
#==============================================================================

# Monitor CI/CD workflows and detect failures
monitor_workflows() {
  echo -e "${BLUE}📊 Monitoring CI/CD Workflows${NC}"

  local branch="${1:-$(git rev-parse --abbrev-ref HEAD)}"
  local commit="${2:-$(git rev-parse HEAD)}"

  echo "Branch: ${branch}"
  echo "Commit: ${commit:0:7}"
  echo ""

  # Get workflow runs for this commit
  local runs=$(github_api_call "/repos/${GITHUB_REPO}/actions/runs?head_sha=${commit}" GET)

  if [ "$(echo "$runs" | jq '.total_count')" -eq 0 ]; then
    echo -e "${YELLOW}⏳ No workflow runs found for this commit yet${NC}"
    return
  fi

  echo -e "${GREEN}Workflow Runs:${NC}"
  echo "$runs" | jq -r '.workflow_runs[] | "\(.name): \(.status) - \(.conclusion // "running")"'

  # Check for failures
  local failures=$(echo "$runs" | jq -r '.workflow_runs[] | select(.conclusion == "failure") | @json')

  if [ -n "$failures" ]; then
    echo ""
    echo -e "${RED}❌ Failed Workflows Detected${NC}"
    echo "$failures" | while IFS= read -r workflow; do
      handle_workflow_failure "$workflow"
    done
  else
    echo ""
    echo -e "${GREEN}✅ All workflows passing${NC}"
  fi
}

# Handle a workflow failure
handle_workflow_failure() {
  local workflow_json="$1"

  local workflow_name=$(echo "$workflow_json" | jq -r '.name')
  local workflow_id=$(echo "$workflow_json" | jq -r '.id')
  local workflow_url=$(echo "$workflow_json" | jq -r '.html_url')

  echo ""
  echo -e "${RED}Failure Details: ${workflow_name}${NC}"
  echo "  URL: ${workflow_url}"

  # Get job details
  local jobs=$(github_api_call "/repos/${GITHUB_REPO}/actions/runs/${workflow_id}/jobs" GET)
  local failed_jobs=$(echo "$jobs" | jq -r '.jobs[] | select(.conclusion == "failure")')

  echo "$failed_jobs" | jq -r '"  Failed Job: \(.name)"'

  # Extract failure logs
  echo ""
  echo -e "${YELLOW}Analyzing failures...${NC}"

  local failure_summary=$(echo "$failed_jobs" | jq -r '.steps[] | select(.conclusion == "failure") | "  - \(.name): \(.conclusion)"')
  echo "$failure_summary"

  # Create GitHub issue for failure
  create_failure_issue "$workflow_name" "$workflow_url" "$failure_summary"

  # Create Beads task for fixing
  create_failure_beads_task "$workflow_name" "$workflow_url"
}

# Create GitHub issue for CI failure
create_failure_issue() {
  local workflow_name="$1"
  local workflow_url="$2"
  local failure_summary="$3"

  local issue_title="CI Failure: ${workflow_name}"
  local issue_body="## CI/CD Failure Detected

**Workflow:** ${workflow_name}
**URL:** ${workflow_url}
**Date:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

### Failed Steps
${failure_summary}

### Action Required
Investigate and fix the failing workflow.

### Related
- Automated detection by AI-Pack
- Check logs for detailed error messages

---
🤖 Auto-generated by ai-pack/scripts/github-mcp-integration.sh"

  echo ""
  echo -e "${BLUE}Creating GitHub issue...${NC}"

  local issue=$(github_api_call "/repos/${GITHUB_REPO}/issues" POST "$(jq -n \
    --arg title "$issue_title" \
    --arg body "$issue_body" \
    '{
      title: $title,
      body: $body,
      labels: ["ci-failure", "automated", "priority-high"]
    }')")

  local issue_number=$(echo "$issue" | jq -r '.number')
  echo -e "${GREEN}✅ Created issue #${issue_number}${NC}"
  echo "   ${workflow_url}"
}

# Create Beads task for CI failure
create_failure_beads_task() {
  local workflow_name="$1"
  local workflow_url="$2"

  if ! command -v bd &> /dev/null; then
    echo -e "${YELLOW}⚠️  Beads not installed, skipping task creation${NC}"
    return
  fi

  local task_id=$(bd create "Fix CI failure: ${workflow_name}" \
    --priority critical \
    --description "CI workflow failing. See: ${workflow_url}" \
    --json | jq -r '.id')

  echo -e "${GREEN}✅ Created Beads task: ${task_id}${NC}"

  # Commit Beads changes
  git add .beads/issues.jsonl
  git commit -m "Add Beads task for CI failure: ${workflow_name}" || true
}

#==============================================================================
# FEATURE 2: Issue/Epic/Story Creation
#==============================================================================

# Sync Beads tasks to GitHub Issues
sync_beads_to_github() {
  echo -e "${BLUE}🔄 Syncing Beads tasks to GitHub Issues${NC}"

  if ! command -v bd &> /dev/null; then
    echo -e "${RED}❌ Beads not installed${NC}"
    exit 1
  fi

  # Get all open Beads tasks
  local beads_tasks=$(bd list --status open --json)

  if [ "$(echo "$beads_tasks" | jq 'length')" -eq 0 ]; then
    echo -e "${YELLOW}No open Beads tasks to sync${NC}"
    return
  fi

  echo "Found $(echo "$beads_tasks" | jq 'length') open Beads tasks"
  echo ""

  echo "$beads_tasks" | jq -c '.[]' | while IFS= read -r task; do
    sync_single_task_to_github "$task"
  done
}

# Sync a single Beads task to GitHub
sync_single_task_to_github() {
  local task_json="$1"

  local task_id=$(echo "$task_json" | jq -r '.id')
  local task_title=$(echo "$task_json" | jq -r '.title')
  local task_desc=$(echo "$task_json" | jq -r '.description // ""')
  local task_priority=$(echo "$task_json" | jq -r '.priority // "normal"')
  local task_assignee=$(echo "$task_json" | jq -r '.assignee // ""')

  # Check if already synced (has github_issue metadata)
  local github_issue=$(echo "$task_json" | jq -r '.metadata.github_issue // ""')

  if [ -n "$github_issue" ]; then
    echo -e "${YELLOW}⏭️  ${task_id} already synced to issue #${github_issue}${NC}"
    return
  fi

  echo -e "${BLUE}Creating issue for ${task_id}: ${task_title}${NC}"

  # Map priority to GitHub labels
  local labels="ai-pack,beads-synced"
  case "$task_priority" in
    critical) labels="${labels},priority-critical" ;;
    high) labels="${labels},priority-high" ;;
    normal) labels="${labels},priority-normal" ;;
    low) labels="${labels},priority-low" ;;
  esac

  # Create issue body
  local issue_body="**Beads Task:** ${task_id}
**Priority:** ${task_priority}

${task_desc}

---
🔗 Synced from Beads task ${task_id}
🤖 Managed by ai-pack"

  # Create GitHub issue
  local issue=$(github_api_call "/repos/${GITHUB_REPO}/issues" POST "$(jq -n \
    --arg title "$task_title" \
    --arg body "$issue_body" \
    --arg labels "$labels" \
    '{
      title: $title,
      body: $body,
      labels: ($labels | split(","))
    }')")

  local issue_number=$(echo "$issue" | jq -r '.number')

  if [ -z "$issue_number" ] || [ "$issue_number" = "null" ]; then
    echo -e "${RED}❌ Failed to create issue${NC}"
    return
  fi

  echo -e "${GREEN}✅ Created issue #${issue_number}${NC}"

  # Update Beads task with GitHub issue reference
  bd comment "$task_id" "GitHub Issue: #${issue_number}"

  # Store metadata (requires Beads metadata support)
  # bd metadata set "$task_id" github_issue "$issue_number"
}

# Create Epic from Beads task and subtasks
create_epic_from_beads() {
  local epic_task_id="$1"

  if [ -z "$epic_task_id" ]; then
    echo "Usage: create_epic_from_beads <beads-task-id>"
    exit 1
  fi

  echo -e "${BLUE}📚 Creating Epic from Beads task ${epic_task_id}${NC}"

  # Get epic task details
  local epic_task=$(bd show "$epic_task_id" --json)
  local epic_title=$(echo "$epic_task" | jq -r '.title')
  local epic_desc=$(echo "$epic_task" | jq -r '.description // ""')

  # Find dependent tasks (subtasks)
  local subtasks=$(bd list --json | jq -r --arg epic "$epic_task_id" \
    '.[] | select(.dependencies[]? == $epic) | @json')

  local subtask_count=$(echo "$subtasks" | wc -l)

  echo "Epic: ${epic_title}"
  echo "Subtasks: ${subtask_count}"
  echo ""

  # Create Epic issue
  local epic_body="# Epic: ${epic_title}

${epic_desc}

## Subtasks
"

  # Add subtask placeholders
  echo "$subtasks" | while IFS= read -r subtask; do
    local subtask_title=$(echo "$subtask" | jq -r '.title')
    epic_body="${epic_body}
- [ ] ${subtask_title}"
  done

  epic_body="${epic_body}

---
🔗 Epic from Beads task ${epic_task_id}
🤖 Managed by ai-pack"

  # Create Epic issue
  local epic_issue=$(github_api_call "/repos/${GITHUB_REPO}/issues" POST "$(jq -n \
    --arg title "Epic: $epic_title" \
    --arg body "$epic_body" \
    '{
      title: $title,
      body: $body,
      labels: ["epic", "ai-pack"]
    }')")

  local epic_number=$(echo "$epic_issue" | jq -r '.number')
  echo -e "${GREEN}✅ Created Epic issue #${epic_number}${NC}"

  # Create subtask issues
  echo ""
  echo -e "${BLUE}Creating subtask issues...${NC}"

  echo "$subtasks" | while IFS= read -r subtask; do
    local subtask_id=$(echo "$subtask" | jq -r '.id')
    local subtask_title=$(echo "$subtask" | jq -r '.title')
    local subtask_desc=$(echo "$subtask" | jq -r '.description // ""')

    local subtask_body="**Beads Task:** ${subtask_id}
**Epic:** #${epic_number}

${subtask_desc}

---
🔗 Part of Epic #${epic_number}
🤖 Managed by ai-pack"

    local subtask_issue=$(github_api_call "/repos/${GITHUB_REPO}/issues" POST "$(jq -n \
      --arg title "$subtask_title" \
      --arg body "$subtask_body" \
      '{
        title: $title,
        body: $body,
        labels: ["story", "ai-pack"]
      }')")

    local subtask_number=$(echo "$subtask_issue" | jq -r '.number')
    echo "  ✅ Created story #${subtask_number}: ${subtask_title}"

    # Link in Beads
    bd comment "$subtask_id" "GitHub Issue: #${subtask_number} (Epic: #${epic_number})"
  done

  echo ""
  echo -e "${GREEN}✅ Epic creation complete${NC}"
  echo "   View: https://github.com/${GITHUB_REPO}/issues/${epic_number}"
}

#==============================================================================
# FEATURE 3: PR Management and Quality Gates
#==============================================================================

# Check PR status and quality gates
check_pr_quality_gates() {
  local pr_number="$1"

  if [ -z "$pr_number" ]; then
    echo "Usage: check_pr_quality_gates <pr-number>"
    exit 1
  fi

  echo -e "${BLUE}🔍 Checking PR #${pr_number} Quality Gates${NC}"
  echo ""

  # Get PR details
  local pr=$(github_api_call "/repos/${GITHUB_REPO}/pulls/${pr_number}" GET)
  local pr_title=$(echo "$pr" | jq -r '.title')
  local pr_head=$(echo "$pr" | jq -r '.head.sha')
  local pr_base=$(echo "$pr" | jq -r '.base.ref')

  echo "PR: ${pr_title}"
  echo "Head: ${pr_head:0:7}"
  echo "Base: ${pr_base}"
  echo ""

  # Check CI status
  echo -e "${BLUE}1. CI/CD Status${NC}"
  local status=$(github_api_call "/repos/${GITHUB_REPO}/commits/${pr_head}/status" GET)
  local state=$(echo "$status" | jq -r '.state')

  case "$state" in
    success)
      echo -e "   ${GREEN}✅ All checks passing${NC}"
      ;;
    pending)
      echo -e "   ${YELLOW}⏳ Checks in progress${NC}"
      ;;
    failure)
      echo -e "   ${RED}❌ Checks failing${NC}"
      local failing=$(echo "$status" | jq -r '.statuses[] | select(.state == "failure") | .context')
      echo "$failing" | while read -r check; do
        echo "      - ${check}"
      done
      ;;
  esac

  # Check for TDD compliance (if ci/tdd-validation exists)
  echo ""
  echo -e "${BLUE}2. TDD Compliance${NC}"
  local tdd_check=$(echo "$status" | jq -r '.statuses[] | select(.context == "ci/tdd-validation") | .state')
  if [ -n "$tdd_check" ]; then
    if [ "$tdd_check" = "success" ]; then
      echo -e "   ${GREEN}✅ TDD validated${NC}"
    else
      echo -e "   ${RED}❌ TDD validation failed${NC}"
    fi
  else
    echo -e "   ${YELLOW}⚠️  TDD validation not configured${NC}"
  fi

  # Check test coverage (if ci/coverage exists)
  echo ""
  echo -e "${BLUE}3. Test Coverage${NC}"
  local coverage_check=$(echo "$status" | jq -r '.statuses[] | select(.context == "ci/coverage") | .state')
  if [ -n "$coverage_check" ]; then
    if [ "$coverage_check" = "success" ]; then
      echo -e "   ${GREEN}✅ Coverage meets threshold${NC}"
    else
      echo -e "   ${RED}❌ Coverage below threshold${NC}"
    fi
  else
    echo -e "   ${YELLOW}⚠️  Coverage check not configured${NC}"
  fi

  # Check for reviews
  echo ""
  echo -e "${BLUE}4. Code Reviews${NC}"
  local reviews=$(github_api_call "/repos/${GITHUB_REPO}/pulls/${pr_number}/reviews" GET)
  local approved=$(echo "$reviews" | jq -r '[.[] | select(.state == "APPROVED")] | length')
  local changes_requested=$(echo "$reviews" | jq -r '[.[] | select(.state == "CHANGES_REQUESTED")] | length')

  echo "   Approved: ${approved}"
  echo "   Changes Requested: ${changes_requested}"

  if [ "$changes_requested" -gt 0 ]; then
    echo -e "   ${RED}❌ Changes requested${NC}"
  elif [ "$approved" -ge 1 ]; then
    echo -e "   ${GREEN}✅ Approved${NC}"
  else
    echo -e "   ${YELLOW}⏳ Awaiting review${NC}"
  fi

  # Overall gate status
  echo ""
  echo -e "${BLUE}Overall Status:${NC}"

  if [ "$state" = "success" ] && [ "$approved" -ge 1 ] && [ "$changes_requested" -eq 0 ]; then
    echo -e "${GREEN}✅ All quality gates passed - ready to merge${NC}"
    return 0
  else
    echo -e "${RED}❌ Quality gates not met${NC}"
    return 1
  fi
}

# Create PR from current branch
create_pr_from_branch() {
  local branch=$(git rev-parse --abbrev-ref HEAD)
  local base="${1:-main}"

  if [ "$branch" = "$base" ]; then
    echo -e "${RED}❌ Cannot create PR from ${base} to ${base}${NC}"
    exit 1
  fi

  echo -e "${BLUE}🔀 Creating PR from ${branch} to ${base}${NC}"

  # Find related Beads task
  local beads_task=""
  if command -v bd &> /dev/null; then
    beads_task=$(bd list --status in_progress --json | jq -r '.[0].id // ""')
  fi

  # Generate PR title and body
  local pr_title="Implement feature from ${branch}"
  local pr_body="## Changes

[Describe changes here]

"

  if [ -n "$beads_task" ]; then
    pr_body="${pr_body}**Beads Task:** ${beads_task}
"
  fi

  pr_body="${pr_body}
## Testing
- [ ] Tests passing
- [ ] Coverage adequate
- [ ] Manual testing complete

## Checklist
- [ ] TDD followed
- [ ] Code reviewed
- [ ] Documentation updated

---
🤖 Created by ai-pack/scripts/github-mcp-integration.sh"

  # Push branch
  echo "Pushing branch..."
  git push -u origin "$branch"

  # Create PR
  local pr=$(github_api_call "/repos/${GITHUB_REPO}/pulls" POST "$(jq -n \
    --arg title "$pr_title" \
    --arg body "$pr_body" \
    --arg head "$branch" \
    --arg base "$base" \
    '{
      title: $title,
      body: $body,
      head: $head,
      base: $base
    }')")

  local pr_number=$(echo "$pr" | jq -r '.number')
  local pr_url=$(echo "$pr" | jq -r '.html_url')

  if [ -z "$pr_number" ] || [ "$pr_number" = "null" ]; then
    echo -e "${RED}❌ Failed to create PR${NC}"
    echo "$pr" | jq '.'
    exit 1
  fi

  echo -e "${GREEN}✅ Created PR #${pr_number}${NC}"
  echo "   ${pr_url}"

  # Link in Beads if task exists
  if [ -n "$beads_task" ]; then
    bd comment "$beads_task" "GitHub PR: #${pr_number} - ${pr_url}"
    echo -e "${GREEN}✅ Linked to Beads task ${beads_task}${NC}"
  fi
}

#==============================================================================
# FEATURE 4: Automated Failure Recovery
#==============================================================================

# Watch for failures and auto-create remediation tasks
watch_and_recover() {
  echo -e "${BLUE}👀 Watching for CI failures (Ctrl+C to stop)${NC}"
  echo ""

  local last_check=$(date +%s)

  while true; do
    local current_time=$(date +%s)

    # Check every 60 seconds
    if [ $((current_time - last_check)) -ge 60 ]; then
      echo "[$(date +%H:%M:%S)] Checking workflows..."

      local recent_runs=$(github_api_call "/repos/${GITHUB_REPO}/actions/runs?per_page=5" GET)
      local failures=$(echo "$recent_runs" | jq -r '.workflow_runs[] | select(.conclusion == "failure" and .created_at > (now - 3600 | todate)) | @json')

      if [ -n "$failures" ]; then
        echo "$failures" | while IFS= read -r workflow; do
          local workflow_id=$(echo "$workflow" | jq -r '.id')

          # Check if we already handled this failure
          if [ -f "/tmp/ai-pack-handled-${workflow_id}" ]; then
            continue
          fi

          echo -e "${RED}🚨 New failure detected${NC}"
          handle_workflow_failure "$workflow"

          # Mark as handled
          touch "/tmp/ai-pack-handled-${workflow_id}"
        done
      fi

      last_check=$current_time
    fi

    sleep 10
  done
}

#==============================================================================
# FEATURE 5: GitHub Projects Integration
#==============================================================================

# Add issues to GitHub Project board
add_to_project() {
  local issue_number="$1"
  local project_number="${2:-1}"

  echo -e "${BLUE}📋 Adding issue #${issue_number} to Project ${project_number}${NC}"

  # Note: GitHub Projects V2 uses GraphQL API
  # This requires the GitHub GraphQL API which is more complex
  # For now, we'll document the capability

  echo -e "${YELLOW}⚠️  GitHub Projects V2 requires GraphQL API${NC}"
  echo "   Manually add to project or implement GraphQL integration"
  echo "   See: https://docs.github.com/en/graphql"
}

#==============================================================================
# CLI Interface
#==============================================================================

show_help() {
  cat << EOF
GitHub MCP Integration for AI-Pack
Version: 1.0.0

Usage: $0 <command> [options]

Commands:
  monitor [branch] [commit]
      Monitor CI/CD workflows for failures
      Examples:
        $0 monitor
        $0 monitor main abc123

  sync-beads
      Sync open Beads tasks to GitHub Issues
      Example:
        $0 sync-beads

  create-epic <beads-task-id>
      Create Epic from Beads task with subtasks
      Example:
        $0 create-epic bd-a1b2

  check-pr <pr-number>
      Check PR quality gates and status
      Example:
        $0 check-pr 123

  create-pr [base-branch]
      Create PR from current branch
      Example:
        $0 create-pr main

  watch
      Watch for CI failures and auto-create remediation tasks
      Example:
        $0 watch

Environment Variables:
  GITHUB_TOKEN        GitHub Personal Access Token (required)
  GITHUB_REPO         Repository in format owner/repo (auto-detected from git)
  GITHUB_MCP_URL      GitHub MCP server URL (default: http://localhost:3000)

Examples:
  # Monitor current branch
  $0 monitor

  # Sync all Beads tasks to GitHub
  $0 sync-beads

  # Create epic from task bd-a1b2
  $0 create-epic bd-a1b2

  # Check PR quality gates
  $0 check-pr 123

  # Create PR from current branch
  $0 create-pr

  # Watch for failures continuously
  $0 watch

For more information, see:
  docs/GITHUB-MCP-INTEGRATION-GUIDE.md
EOF
}

# Main CLI router
main() {
  if [ $# -eq 0 ]; then
    show_help
    exit 0
  fi

  local command="$1"
  shift

  case "$command" in
    monitor)
      monitor_workflows "$@"
      ;;
    sync-beads)
      sync_beads_to_github
      ;;
    create-epic)
      create_epic_from_beads "$@"
      ;;
    check-pr)
      check_pr_quality_gates "$@"
      ;;
    create-pr)
      create_pr_from_branch "$@"
      ;;
    watch)
      watch_and_recover
      ;;
    help|--help|-h)
      show_help
      ;;
    *)
      echo -e "${RED}❌ Unknown command: $command${NC}"
      echo ""
      show_help
      exit 1
      ;;
  esac
}

# Run main if executed directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  main "$@"
fi
