package protocol_handler

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Register registers the agent:// protocol handler for the current platform
func Register() error {
	switch runtime.GOOS {
	case "darwin":
		return registerMacOS()
	case "linux":
		return registerLinux()
	case "windows":
		return registerWindows()
	default:
		return fmt.Errorf("protocol handler registration not supported on %s", runtime.GOOS)
	}
}

// IsRegistered checks if the agent:// protocol handler is already registered
func IsRegistered() bool {
	switch runtime.GOOS {
	case "darwin":
		return isRegisteredMacOS()
	case "linux":
		return isRegisteredLinux()
	case "windows":
		return isRegisteredWindows()
	default:
		return false
	}
}

// registerMacOS registers the protocol handler on macOS
func registerMacOS() error {
	// Get the path to the current executable
	exePath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("failed to get executable path: %w", err)
	}

	// Create a handler script that will be registered
	handlerScript := filepath.Join(filepath.Dir(exePath), "agent_protocol_handler.sh")
	scriptContent := fmt.Sprintf(`#!/bin/bash
# AI-Pack agent:// protocol handler for macOS
# Auto-generated by agent-server

AGENT_URL="$1"

# Call agent-server with the URL
"%s" "$AGENT_URL"
`, exePath)

	if err := os.WriteFile(handlerScript, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("failed to create handler script: %w", err)
	}

	// Register using SwiftDefaultApps if available, otherwise provide instructions
	fmt.Println("🔗 Registering agent:// protocol handler...")
	fmt.Println()
	fmt.Println("📋 Manual registration required on macOS:")
	fmt.Println()
	fmt.Println("1. Run this command to register:")
	fmt.Printf("   open -a Terminal.app '%s'\n", handlerScript)
	fmt.Println()
	fmt.Println("2. Or create an Automator app:")
	fmt.Println("   - Open Automator")
	fmt.Println("   - Create new Application")
	fmt.Println("   - Add 'Run Shell Script' action")
	fmt.Printf("   - Paste: %s \"$@\"\n", exePath)
	fmt.Println("   - Save as 'AI-Pack Handler.app'")
	fmt.Println()
	fmt.Println("3. Then register with Launch Services:")
	fmt.Println("   /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f '/Applications/AI-Pack Handler.app'")
	fmt.Println()
	fmt.Printf("✅ Handler script created: %s\n", handlerScript)

	return nil
}

// isRegisteredMacOS checks if the handler is registered on macOS
func isRegisteredMacOS() bool {
	cmd := exec.Command("/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister", "-dump")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(output), "agent:")
}

// registerLinux registers the protocol handler on Linux
func registerLinux() error {
	exePath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("failed to get executable path: %w", err)
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	// Create .desktop file
	desktopDir := filepath.Join(homeDir, ".local", "share", "applications")
	if err := os.MkdirAll(desktopDir, 0755); err != nil {
		return fmt.Errorf("failed to create applications directory: %w", err)
	}

	desktopFile := filepath.Join(desktopDir, "ai-pack-agent-handler.desktop")
	desktopContent := fmt.Sprintf(`[Desktop Entry]
Type=Application
Name=AI-Pack Agent Handler
Exec=%s %%u
MimeType=x-scheme-handler/agent;
NoDisplay=true
`, exePath)

	if err := os.WriteFile(desktopFile, []byte(desktopContent), 0644); err != nil {
		return fmt.Errorf("failed to create desktop file: %w", err)
	}

	// Update desktop database
	if err := exec.Command("update-desktop-database", desktopDir).Run(); err != nil {
		fmt.Printf("⚠️  Could not update desktop database: %v\n", err)
		fmt.Println("   Run manually: update-desktop-database ~/.local/share/applications")
	}

	// Set as default handler
	if err := exec.Command("xdg-mime", "default", "ai-pack-agent-handler.desktop", "x-scheme-handler/agent").Run(); err != nil {
		fmt.Printf("⚠️  Could not set default handler: %v\n", err)
		fmt.Println("   Run manually: xdg-mime default ai-pack-agent-handler.desktop x-scheme-handler/agent")
	}

	fmt.Printf("✅ Protocol handler registered: %s\n", desktopFile)
	return nil
}

// isRegisteredLinux checks if the handler is registered on Linux
func isRegisteredLinux() bool {
	cmd := exec.Command("xdg-mime", "query", "default", "x-scheme-handler/agent")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return strings.Contains(string(output), "ai-pack-agent-handler.desktop")
}

// registerWindows registers the protocol handler on Windows
func registerWindows() error {
	exePath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("failed to get executable path: %w", err)
	}

	// Use reg.exe to add registry keys
	commands := [][]string{
		{"reg", "add", "HKCU\\Software\\Classes\\agent", "/ve", "/d", "URL:AI-Pack Agent Protocol", "/f"},
		{"reg", "add", "HKCU\\Software\\Classes\\agent", "/v", "URL Protocol", "/d", "", "/f"},
		{"reg", "add", "HKCU\\Software\\Classes\\agent\\shell\\open\\command", "/ve", "/d", fmt.Sprintf("\"%s\" \"%%1\"", exePath), "/f"},
	}

	for _, cmdArgs := range commands {
		cmd := exec.Command(cmdArgs[0], cmdArgs[1:]...)
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("failed to register protocol: %w", err)
		}
	}

	fmt.Println("✅ Protocol handler registered in Windows registry")
	return nil
}

// isRegisteredWindows checks if the handler is registered on Windows
func isRegisteredWindows() bool {
	cmd := exec.Command("reg", "query", "HKCU\\Software\\Classes\\agent")
	return cmd.Run() == nil
}
